### ISSUE TITLE
scan qr error

### ISSUE THREAD

**Issue by Huguitis** [phaticusthiccy/WhatsAsenaDuplicated#214]
WARN     [2021-10-21 13:34:51.198 +0000] (106): connect attempt 5 failed: Error: close, retrying...
    error: {}
    class: "Baileys"

**Comment by david-lev** [comment]
I have the same problem.
Trying to scan the qr code in [this](https://repl.it/@phaticusthiccy/WhatsAsena-QR#index.js) link and getting this error:

![image](https://user-images.githubusercontent.com/42866208/163457999-34aa83ad-9358-4174-ac1d-810c3deaa08a.png)

**Comment by phaticusthiccy** [comment]
Hello. Many people encounter the error in the photo you sent. Let me explain this.

A long time ago, WhatsApp made a system that can work without an internet connection. In short, multi-device support. While this update was very good for users, it turned into a nightmare for developers and API services.

We, the developers, want a system or server to work fast and stable, but the multi-device feature of whatsapp works very differently.

WhatsAsena uses web sockets to connect to whatsapp web. It does this with the Baileys framework.
Whatsapp API systems that were stable before have become experimental with this new feature. The version currently in use is really old, I have to rewrite about 50,000 lines of code to update it. Moreover, I need to convert the previously used NodeJS language to Typescript. New sockets unfortunately run very slowly in NodeJS programs.

I tested the new version locally and came to the conclusion that:

Pluses:
* Sockets have really fast connections within themselves.
* CommonJS module works with 100% performance.
* Messages are transmitted instantly even when the mobile device is disabled.

Cons:
* Sockets are refreshed every 10 seconds or every message.
* After scanning the QR codes, the whatsapp connection must be closed in order for the sockets to remain open.
* Installation time is very long for connections in opened sockets, it can take up to 20 minutes if you have a lot of chat bubbles
* User ID uploaded to any server expires before a socket connection can be established.


Since WhatsAsena is an open-source project, the development stages may differ. I will not give any update for this in this case. As we said before, it's hard to tell the next update date. If you are looking for our alternatives, check out Nurutomo's original bot. Remember, except the bot I mentioned above and WhatsAsena, other projects you can find are 95% likely stolen.

Have a nice day

**Comment by david-lev** [comment]
I suspected that these about linked devices .. Thanks for the detailed explanation and good luck!
