### ISSUE TITLE
Lydia

### ISSUE THREAD

**Issue by thecyberbyte-tech** [phaticusthiccy/WhatsAsenaDuplicated#55]
Lydia.js is not working perfectly please fix it soon

https://github.com/phaticusthiccy/WhatsAsenaDuplicated/blob/master/plugins/lydia.js

It's showing typing but do not send any msg

i had a conversation with intellivoid team,they said the issue is caused by Respected userbot coding not by us and we're not going fix this problem cause we are not owner of that userbot

**Comment by phaticusthiccy** [comment]
### Hi @thecyberbyte-tech 😉
##
##### Bug Definition 🕷️

> Reason

**This error is caused by the coffehouse. We are using**[Coffehouse JavaScript API Wrapper](https://github.com/intellivoid/CoffeeHouse-JavaScript-API-Wrapper) **written by** [Yusuf Usta](https://github.com/yusufusta).
**I need to update** [lydia.js](https://github.com/phaticusthiccy/WhatsAsenaDuplicated/blob/master/plugins/lydia.js) 

> New Update?

**Maybe I can fix it until the new update arrives.**
**I don't want to promise for this..**

##

**Comment by thecyberbyte-tech** [comment]
i had a conversation with intellivoid team,they said the issue is caused by Respected userbot coding not by us and we're not going fix this problem cause we are not owner of that userbot

**Comment by phaticusthiccy** [comment]
Hello again @thecyberbyte-tech 

I haven't had the opportunity to look through the codes until now. I edited the codes about 1 hour ago. Lydia works perfectly. 
Please wait for new update.

Thanks for your valuable opinion and effort. 
Issues Closed 🙋🏻

**Comment by phaticusthiccy** [comment]
Sorry, my previous message was misspelled. When I say the problem is coffeehouse, I wanted to mean our lydia.js 
Ups :)
