### ISSUE TITLE
Bot reply mismatch chats

### ISSUE THREAD

**Issue by rushi4tg** [phaticusthiccy/WhatsAsenaDuplicated#91]
the bot replys(output) for the given command in random chats sometimes.
example:-
I send .alive to xyz person/group chat
The .alive msg is deleted from the xyz person/group chat
But the output of .alive is sent to abc person/group!
And the xyz person/group chat dont get output msg..

**Comment by rushi4tg** [comment]
Also .faceai and .animai dont work for me
And .img command throughs error in heroku log and bot restart
btw,thanks for this awesome ,your hardwork for maintaing the bot is pro _/ \_

**Comment by sam-pandey** [comment]
yeah,Same issue

**Comment by phaticusthiccy** [comment]
> the bot replys(output) for the given command in random chats sometimes.
> example:-
> I send .alive to xyz person/group chat
> The .alive msg is deleted from the xyz person/group chat
> But the output of .alive is sent to abc person/group!
> And the xyz person/group chat dont get output msg..

Hi @rushi4tg 
Firstly sorry for late reply.
This Issue caused by server delay, so ı mean ping.
Ping value refers to the speed of your connection to the server. (1000ms = 1 second)
Bailyes and we are using **message.jid**
This means that; Every messages had own unique values. And every groups and chats has their own values. Like 991xxxx-12345@g.us or 991....@s.whatsapp.net
Sometimes (when your ping is high) it will send messages another chats.
This and the older WhatsAsena versions are used to send message with a new message.jid checker. Here is the mini example for you:
```js
await message.client.sendMessage(
    message.jid, 
    'Test One',
    MessageType.text
) // We can send a new message with instant message.jid
await message.client.sendMessage(
    message.jid, 
    'Test Two',
    MessageType.text
) // And another message with instant message.jid again.
```
Now, we are using one more time this message.jid. 
It will check one more time. Example for you:
```js
var id = message.jid
await message.client.sendMessage(
    id, 
    'New Test One',
    MessageType.text
)  // New message with first message.jid
await message.client.sendMessage(
    id, 
    'New Test Two',
    MessageType.text
)  // Again, new message with the first message.jid
```
This thing will improve general stability. And also this thing will mostly solve this issue.
